-- Seed activities for Hub dashboard
INSERT INTO activities (type, app, actor_name, actor_avatar, data, created_at) VALUES
  ('post_created', 'social', 'admin', NULL, '{"body": "Just shipped a new feature for the platform!"}', NOW() - INTERVAL '2 hours'),
  ('post_created', 'social', 'spark', NULL, '{"body": "Working on the Hub activity feed"}', NOW() - INTERVAL '3 hours'),
  ('score_submitted', 'arcade', 'admin', NULL, '{"game": "Snake", "score": 4200}', NOW() - INTERVAL '4 hours'),
  ('score_submitted', 'arcade', 'pixel', NULL, '{"game": "Tetris", "score": 15800}', NOW() - INTERVAL '5 hours'),
  ('score_submitted', 'arcade', 'blitz', NULL, '{"game": "Breakout", "score": 8900}', NOW() - INTERVAL '6 hours'),
  ('event_created', 'events', 'admin', NULL, '{"title": "Platform Demo Day"}', NOW() - INTERVAL '7 hours'),
  ('rsvp', 'events', 'spark', NULL, '{"event": "Platform Demo Day", "status": "going"}', NOW() - INTERVAL '8 hours'),
  ('rsvp', 'events', 'relay', NULL, '{"event": "Platform Demo Day", "status": "going"}', NOW() - INTERVAL '8 hours 30 minutes'),
  ('server_created', 'minecraft', 'admin', NULL, '{"name": "Creative World"}', NOW() - INTERVAL '1 day'),
  ('server_started', 'minecraft', 'admin', NULL, '{"name": "Creative World"}', NOW() - INTERVAL '1 day'),
  ('post_created', 'social', 'relay', NULL, '{"body": "The cross-app navigation is looking great"}', NOW() - INTERVAL '1 day 2 hours'),
  ('score_submitted', 'arcade', 'echo', NULL, '{"game": "Memory", "score": 12000}', NOW() - INTERVAL '1 day 4 hours'),
  ('event_created', 'events', 'ember', NULL, '{"title": "Weekly Standup"}', NOW() - INTERVAL '2 days'),
  ('rsvp', 'events', 'volt', NULL, '{"event": "Weekly Standup", "status": "maybe"}', NOW() - INTERVAL '2 days 1 hour'),
  ('server_created', 'minecraft', 'core', NULL, '{"name": "Survival Server"}', NOW() - INTERVAL '2 days 3 hours'),
  ('post_created', 'social', 'wave', NULL, '{"body": "Just explored the new Hub dashboard"}', NOW() - INTERVAL '3 days'),
  ('score_submitted', 'arcade', 'rune', NULL, '{"game": "Typing", "score": 9500}', NOW() - INTERVAL '3 days 2 hours'),
  ('server_started', 'minecraft', 'core', NULL, '{"name": "Survival Server"}', NOW() - INTERVAL '3 days 4 hours'),
  ('event_created', 'events', 'tide', NULL, '{"title": "Game Night"}', NOW() - INTERVAL '4 days'),
  ('rsvp', 'events', 'blitz', NULL, '{"event": "Game Night", "status": "going"}', NOW() - INTERVAL '4 days 1 hour');
