apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: PROJECT_NAME
  namespace: APP_NAMESPACE
spec:
  ingressClassName: traefik
  rules:
    - host: __SERVICE_PREFIX__console.__PLATFORM_DOMAIN__
      http:
        paths:
          - path: /ws/terminal
            pathType: Prefix
            backend:
              service:
                name: PROJECT_NAME
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: PROJECT_NAME
                port:
                  number: 80
