apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-manager
  namespace: APP_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecraft-manager
  namespace: APP_NAMESPACE
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecraft-manager
  namespace: APP_NAMESPACE
subjects:
  - kind: ServiceAccount
    name: minecraft-manager
    namespace: APP_NAMESPACE
roleRef:
  kind: Role
  name: minecraft-manager
  apiGroup: rbac.authorization.k8s.io
