apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jitsi.yaml
  - mailpit.yaml
  - oauth2-proxy.yaml
  - op-api-rbac.yaml
  - woodpecker-rbac.yaml
  - woodpecker.yaml
  - zulip.yaml
