apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: woodpecker
  namespace: flux-system
spec:
  interval: 12h
  url: https://woodpecker-ci.org/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: woodpecker
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
