mode: standalone
replicas: 1
existingSecret: minio-credentials
persistence:
  enabled: true
  size: 20Gi
resources:
  requests:
    memory: 256Mi
nodeSelector:
  kubernetes.io/hostname: otavert-vxrail
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - s3.product-garden.com
consoleIngress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - minio.product-garden.com
