when:
  - event: push
    branch: main

steps:
  - name: build
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: forgejo.dev.test
      repo: forgejo.dev.test/${CI_REPO_OWNER}/${CI_REPO_NAME}
      tags:
        - "${CI_COMMIT_SHA:0:8}"
        - latest
      skip_tls_verify: true
      username:
        from_secret: registry_username
      password:
        from_secret: registry_token

  - name: deploy
    image: bitnami/kubectl:latest
    commands:
      - kubectl set image deployment/app app=forgejo.dev.test/${CI_REPO_OWNER}/${CI_REPO_NAME}:${CI_COMMIT_SHA:0:8} -n ${CI_REPO_NAME}
      - kubectl rollout status deployment/app -n ${CI_REPO_NAME} --timeout=120s
    backend_options:
      kubernetes:
        serviceAccount: woodpecker-pipeline
