apiVersion: v1
kind: Service
metadata:
  name: jitsi-oidc
  namespace: jitsi
spec:
  selector:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: jitsi
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jitsi-oidc
  namespace: jitsi
spec:
  ingressClassName: traefik
  rules:
    - host: meet-auth.open-platform.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jitsi-oidc
                port:
                  number: 80
