apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  enableSuperuserAccess: true
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-credentials
      postInitSQL:
        - CREATE DATABASE platform_ledger
        - CREATE DATABASE product_garden
        # BEGIN zulip
        - CREATE DATABASE zulip
        - CREATE ROLE zulip WITH LOGIN
        - ALTER DATABASE zulip OWNER TO zulip
        # END zulip
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
    # BEGIN pgadmin
    pg_hba:
      - host all postgres 10.42.0.0/16 trust
      - host all postgres 10.43.0.0/16 trust
    # END pgadmin
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
