apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: woodpecker-deployer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["services", "secrets", "configmaps", "pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: woodpecker-pipeline
  namespace: woodpecker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: woodpecker-deployer
subjects:
  - kind: ServiceAccount
    name: woodpecker-agent
    namespace: woodpecker
roleRef:
  kind: ClusterRole
  name: woodpecker-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: woodpecker-pipeline-deployer
subjects:
  - kind: ServiceAccount
    name: woodpecker-pipeline
    namespace: woodpecker
roleRef:
  kind: ClusterRole
  name: woodpecker-deployer
  apiGroup: rbac.authorization.k8s.io
