apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: identity
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: open-platform
  path: ./identity
  prune: true
  wait: true
