clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true

when:
  - event: [push, manual]
    branch: main

steps:
  - name: build
    image: woodpeckerci/plugin-kaniko
    settings:
      repo: ${CI_REPO_OWNER}/${CI_REPO_NAME}
      registry:
        from_secret: registry_host
      tags:
        - "${CI_COMMIT_SHA:0:8}"
        - latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_token
      skip_tls_verify: true
      cache: true
      cache_repo: ${CI_REPO_OWNER}/cache
      build_args:
        - BUILDKIT_INLINE_CACHE=1
