add_newline = false
format = "$directory$git_branch$git_status$kubernetes$cmd_duration$character"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[kubernetes]
disabled = false
symbol = "⎈ "
style = "bold blue"
format = "[$symbol$context( \\($namespace\\))]($style) "

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"
