apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - traefik-tls.yaml
  - minio.yaml
  - postgres-cluster.yaml
  - oauth2-proxy-middleware.yaml
  - cloudflared.yaml
