apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: v1
kind: Namespace
metadata:
  name: woodpecker
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-system-social
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "system"
    platform.dev.test/repo: "social"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-system-minecraft
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "system"
    platform.dev.test/repo: "minecraft"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-system-hub
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "system"
    platform.dev.test/repo: "hub"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-system-arcade
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "system"
    platform.dev.test/repo: "arcade"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-system-events
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "system"
    platform.dev.test/repo: "events"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-foundry-pulse
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "foundry"
    platform.dev.test/repo: "pulse"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: op-foundry-craft
  labels:
    platform.dev.test/managed: "true"
    platform.dev.test/org: "foundry"
    platform.dev.test/repo: "craft"
    platform.dev.test/tier: "workload"
    platform.dev.test/environment: "production"
