{{- if and (eq .Values.infrastructure.mode "bundled") (eq .Values.tls.mode "letsencrypt") }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    {{- include "op.labels" . | nindent 4 }}
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
{{- end }}
