{{- if eq .Values.infrastructure.mode "bundled" }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
  labels:
    {{- include "op.labels" . | nindent 4 }}
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    {{- if .Values.multinode.enabled }}
    nodeSelector:
      open-platform.sh/node-role: infra
    {{- end }}
    mode: standalone
    replicas: 1
    existingSecret: minio-credentials
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: 256Mi
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - {{ include "op.svcHost" (list . "s3") }}
    consoleIngress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - {{ include "op.svcHost" (list . "minio") }}
    oidc:
      enabled: true
      configUrl: "{{ include "op.forgejoUrl" . }}/.well-known/openid-configuration"
      existingClientSecretName: "minio-oidc-credentials"
      existingClientIdKey: "client-id"
      existingClientSecretKey: "client-secret"
      claimName: "groups"
      scopes: "openid,profile,email,groups"
      redirectUri: "https://{{ include "op.svcHost" (list . "minio") }}/oauth_callback"
      displayName: "Forgejo"
    environment:
      MINIO_IDENTITY_OPENID_CLAIM_USERINFO: "on"
    policies:
      - name: system
        statements:
          - effect: Allow
            resources:
              - 'arn:aws:s3:::*'
            actions:
              - "s3:*"
          - effect: Allow
            resources:
              - 'arn:aws:s3:::*'
            actions:
              - "admin:*"
    {{- if ne (include "op.tlsMode" .) "letsencrypt" }}
    extraVolumes:
      - name: platform-ca
        configMap:
          name: platform-ca
    extraVolumeMounts:
      - name: platform-ca
        mountPath: /etc/ssl/certs/platform-ca.crt
        subPath: ca.crt
        readOnly: true
    {{- end }}
{{- end }}
