apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provisioner.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
data:
  reconciler.sh: {{ .Files.Get "scripts/reconciler.sh" | quote }}
  health-check.sh: {{ .Files.Get "scripts/health-check.sh" | quote }}
