schedule:
  reconciler: "*/1 * * * *"
  healthCheck: "*/5 * * * *"

forgejo:
  internalUrl: "http://forgejo-http.forgejo.svc.cluster.local:3000"
  secretName: "provisioner-forgejo"

db:
  secretName: "provisioner-db"
  consoleDatabaseName: "op_system_console"

platform:
  domain: ""
  repoUrl: "system/open-platform"

image:
  repository: alpine/helm
  tag: "3.16.4"

initImage:
  repository: alpine/git
  tag: "latest"

healthImage:
  repository: alpine
  tag: "latest"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
