apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: op-api
  namespace: APP_NAMESPACE
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: SERVICE_PREFIXapi.PLATFORM_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: op-api
                port:
                  number: 80
  tls:
    - hosts:
        - SERVICE_PREFIXapi.PLATFORM_DOMAIN
      secretName: wildcard-tls
